// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* TemperatureService_method_names[] = {
  "/TemperatureService/StreamTemperature",
};

std::unique_ptr< TemperatureService::Stub> TemperatureService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TemperatureService::Stub> stub(new TemperatureService::Stub(channel, options));
  return stub;
}

TemperatureService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamTemperature_(TemperatureService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::TemperatureData>* TemperatureService::Stub::StreamTemperatureRaw(::grpc::ClientContext* context, const ::StreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::TemperatureData>::Create(channel_.get(), rpcmethod_StreamTemperature_, context, request);
}

void TemperatureService::Stub::async::StreamTemperature(::grpc::ClientContext* context, const ::StreamRequest* request, ::grpc::ClientReadReactor< ::TemperatureData>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::TemperatureData>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamTemperature_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::TemperatureData>* TemperatureService::Stub::AsyncStreamTemperatureRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::TemperatureData>::Create(channel_.get(), cq, rpcmethod_StreamTemperature_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::TemperatureData>* TemperatureService::Stub::PrepareAsyncStreamTemperatureRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::TemperatureData>::Create(channel_.get(), cq, rpcmethod_StreamTemperature_, context, request, false, nullptr);
}

TemperatureService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TemperatureService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< TemperatureService::Service, ::StreamRequest, ::TemperatureData>(
          [](TemperatureService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StreamRequest* req,
             ::grpc::ServerWriter<::TemperatureData>* writer) {
               return service->StreamTemperature(ctx, req, writer);
             }, this)));
}

TemperatureService::Service::~Service() {
}

::grpc::Status TemperatureService::Service::StreamTemperature(::grpc::ServerContext* context, const ::StreamRequest* request, ::grpc::ServerWriter< ::TemperatureData>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


